import 'package:flutter/cupertino.dart';
import 'package:happiness_club/constants/storage_keys.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LatestOffersModelData {
/*
{
  "id": 225,
  "end_date": "2019-07-10",
  "title": "Dubai Library Distributors",
  "offer_discount": "20 %",
  "featured_image": null,
  "offer_logo_type": "1",
  "view_count": 0,
  "category_id": 11,
  "category_name": "Others",
  "image_gallery": null,
  "coordinates": null,
  "distance": 0.11
}
*/

  int? id;
  String? endDate;
  String? title;
  String? offerDiscount;
  String? featuredImage;
  String? offerLogoType;
  int? viewCount;
  int? categoryId;
  String? categoryName;
  String? imageGallery;
  String? coordinates;
  double? distance;

  LatestOffersModelData({
    this.id,
    this.endDate,
    this.title,
    this.offerDiscount,
    this.featuredImage,
    this.offerLogoType,
    this.viewCount,
    this.categoryId,
    this.categoryName,
    this.imageGallery,
    this.coordinates,
    this.distance,
  });
  LatestOffersModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    endDate = json['end_date']?.toString();
    title = json['title']?.toString();
    offerDiscount = json['offer_discount']?.toString();
    featuredImage = json['featured_image']?.toString();
    offerLogoType = json['offer_logo_type']?.toString();
    viewCount = json['view_count']?.toInt();
    categoryId = json['category_id']?.toInt();
    categoryName = json['category_name']?.toString();
    imageGallery = json['image_gallery']?.toString();
    coordinates = json['coordinates']?.toString();
    distance = json['distance']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['end_date'] = endDate;
    data['title'] = title;
    data['offer_discount'] = offerDiscount;
    data['featured_image'] = featuredImage;
    data['offer_logo_type'] = offerLogoType;
    data['view_count'] = viewCount;
    data['category_id'] = categoryId;
    data['category_name'] = categoryName;
    data['image_gallery'] = imageGallery;
    data['coordinates'] = coordinates;
    data['distance'] = distance;
    return data;
  }
}

class LatestOffersModel {
/*
{
  "responseStatus": "success",
  "message": "",
  "data": [
    {
      "id": 225,
      "end_date": "2019-07-10",
      "title": "Dubai Library Distributors",
      "offer_discount": "20 %",
      "featured_image": null,
      "offer_logo_type": "1",
      "view_count": 0,
      "category_id": 11,
      "category_name": "Others",
      "image_gallery": null,
      "coordinates": null,
      "distance": 0.11
    }
  ]
}
*/

  String? responseStatus;
  String? message;
  List<LatestOffersModelData?>? data;

  LatestOffersModel({
    this.responseStatus,
    this.message,
    this.data,
  });
  LatestOffersModel.fromJson(Map<String, dynamic> json) {
    responseStatus = json['responseStatus']?.toString();
    message = json['message']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <LatestOffersModelData>[];
      v.forEach((v) {
        arr0.add(LatestOffersModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['responseStatus'] = responseStatus;
    data['message'] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}


class LatestOffersProvider extends ChangeNotifier{
  LatestOffersModel? modelData ;
  String state = StorageKeys.STATE_LOADING;
  addModelData(LatestOffersModel data){
    modelData = null;
    modelData = data;
    state = StorageKeys.STATE_FINISHED;
    notifyListeners();
  }

  clearProvider(){
    state = StorageKeys.STATE_LOADING;
    modelData = null;
    notifyListeners();

  }
}