///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AboutUsModelDataVideos {

  String? videoImage;
  String? videoLink;

  AboutUsModelDataVideos({
    this.videoImage,
    this.videoLink,
  });
  AboutUsModelDataVideos.fromJson(Map<String, dynamic> json) {
    videoImage = json['video_image']?.toString();
    videoLink = json['video_link']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['video_image'] = videoImage;
    data['video_link'] = videoLink;
    return data;
  }
}

class AboutUsModelData {
  String? content;
  String? totalMembers;
  String? totalPartners;
  String? totalChampions;
  String? totalCompanies;
  List<AboutUsModelDataVideos?>? videos;

  AboutUsModelData({
    this.content,
    this.totalMembers,
    this.totalPartners,
    this.totalChampions,
    this.totalCompanies,
    this.videos,
  });
  AboutUsModelData.fromJson(Map<String, dynamic> json) {
    content = json['content']?.toString();
    totalMembers = json['total_members']?.toString();
    totalPartners = json['total_partners']?.toString();
    totalChampions = json['total_champions']?.toString();
    totalCompanies = json['total_companies']?.toString();
    if (json['videos'] != null) {
      final v = json['videos'];
      final arr0 = <AboutUsModelDataVideos>[];
      v.forEach((v) {
        arr0.add(AboutUsModelDataVideos.fromJson(v));
      });
      videos = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['content'] = content;
    data['total_members'] = totalMembers;
    data['total_partners'] = totalPartners;
    data['total_champions'] = totalChampions;
    data['total_companies'] = totalCompanies;
    if (videos != null) {
      final v = videos;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['videos'] = arr0;
    }
    return data;
  }
}

class AboutUsModel {
  String? responseStatus;
  String? message;
  AboutUsModelData? data;

  AboutUsModel({
    this.responseStatus,
    this.message,
    this.data,
  });
  AboutUsModel.fromJson(Map<String, dynamic> json) {
    responseStatus = json['responseStatus']?.toString();
    message = json['message']?.toString();
    data = (json['data'] != null) ? AboutUsModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['responseStatus'] = responseStatus;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
