///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AnnouncementModelData {
/*
{
  "id": 2,
  "title": "Happy New Year 2022",
  "description": "<p>This initiative was started with three goals in mind, Enjoyment, Inspiration, and Work Smart. With over 61,000+ members and 3000+ partners, the Happiness Club aims to bring our members and partners together into a beneficial relationship.</p>",
  "announcement_date": "2021-12-25",
  "status": 1,
  "created_at": "2021-12-25 19:26:09",
  "updated_at": "2021-12-25 19:26:09"
}
*/

  int? id;
  String? title;
  String? description;
  String? announcementDate;
  int? status;
  String? createdAt;
  String? updatedAt;

  AnnouncementModelData({
    this.id,
    this.title,
    this.description,
    this.announcementDate,
    this.status,
    this.createdAt,
    this.updatedAt,
  });
  AnnouncementModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    description = json['description']?.toString();
    announcementDate = json['announcement_date']?.toString();
    status = json['status']?.toInt();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['description'] = description;
    data['announcement_date'] = announcementDate;
    data['status'] = status;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}

class AnnouncementModel {
/*
{
  "responseStatus": "success",
  "message": "",
  "data": [
    {
      "id": 2,
      "title": "Happy New Year 2022",
      "description": "<p>This initiative was started with three goals in mind, Enjoyment, Inspiration, and Work Smart. With over 61,000+ members and 3000+ partners, the Happiness Club aims to bring our members and partners together into a beneficial relationship.</p>",
      "announcement_date": "2021-12-25",
      "status": 1,
      "created_at": "2021-12-25 19:26:09",
      "updated_at": "2021-12-25 19:26:09"
    }
  ]
}
*/

  String? responseStatus;
  String? message;
  List<AnnouncementModelData?>? data;

  AnnouncementModel({
    this.responseStatus,
    this.message,
    this.data,
  });
  AnnouncementModel.fromJson(Map<String, dynamic> json) {
    responseStatus = json['responseStatus']?.toString();
    message = json['message']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <AnnouncementModelData>[];
      v.forEach((v) {
        arr0.add(AnnouncementModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['responseStatus'] = responseStatus;
    data['message'] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
