///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PrizeHistoryModelData {
/*
{
  "id": 2,
  "full_name": "Babar Aslam",
  "photo": "",
  "gift_title": "T-shirt"
}
*/

  int? id;
  String? fullName;
  String? photo;
  String? giftTitle;

  PrizeHistoryModelData({
    this.id,
    this.fullName,
    this.photo,
    this.giftTitle,
  });
  PrizeHistoryModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    fullName = json['full_name']?.toString();
    photo = json['photo']?.toString();
    giftTitle = json['gift_title']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['full_name'] = fullName;
    data['photo'] = photo;
    data['gift_title'] = giftTitle;
    return data;
  }
}

class PrizeHistoryModel {
/*
{
  "responseStatus": "success",
  "message": "",
  "data": [
    {
      "id": 2,
      "full_name": "Babar Aslam",
      "photo": "",
      "gift_title": "T-shirt"
    }
  ]
}
*/

  String? responseStatus;
  String? message;
  List<PrizeHistoryModelData?>? data;

  PrizeHistoryModel({
    this.responseStatus,
    this.message,
    this.data,
  });
  PrizeHistoryModel.fromJson(Map<String, dynamic> json) {
    responseStatus = json['responseStatus']?.toString();
    message = json['message']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <PrizeHistoryModelData>[];
      v.forEach((v) {
        arr0.add(PrizeHistoryModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['responseStatus'] = responseStatus;
    data['message'] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
